### ISSUE TITLE
change the alarm sound to a new!

### ISSUE THREAD

**Issue by Sushant2** [Sushant2/Clockworks#1]
Attach a new sound track when time ends from a beep sound!

**Comment by Ramlanisagar** [comment]
@Sushant2  for contribution I have to change only MP3 file. please correct me if I am wrong

**Comment by Sushant2** [comment]
> @Sushant2 for contribution I have to change only MP3 file. please correct me if I am wrong

Yes, U'll need a new sound track & do some changes in JS file too!
Acc. to the new track!

**Comment by Sushant2** [comment]
Thanks @badal-cloud for ur contribution to this repo!!
