### ISSUE TITLE
Update README file & Time text!!!

### ISSUE THREAD

**Issue by Sushant2** [Sushant2/Clockworks#3]
Update the README according to new site & write current time in front of running time!!!

**Comment by gabrielmarques0** [comment]
Hey, I'd like to work on this. What do you mean by `write current time in front of running time`?

**Comment by bhantsi** [comment]
Hey! Did you mean to display time along with the timer?

**Comment by Sushant2** [comment]
Check the site!
The current time is running on it!
Write the "Current Time" in front of it!!!
